"""Initial database schema

Revision ID: 5830422f9b77
Revises: 
Create Date: 2025-09-30 01:15:24.542419+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5830422f9b77"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extensions",
        sa.Column(
            "extension_id",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for the extension",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Extension name (must be unique)",
        ),
        sa.Column(
            "display_name",
            sa.String(length=150),
            nullable=False,
            comment="Human-readable display name",
        ),
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=False,
            comment="Extension description",
        ),
        sa.Column(
            "version",
            sa.String(length=20),
            nullable=False,
            comment="Extension version (semver format)",
        ),
        sa.Column(
            "author", sa.String(length=100), nullable=False, comment="Extension author"
        ),
        sa.Column(
            "author_email", sa.String(length=255), nullable=True, comment="Author email"
        ),
        sa.Column(
            "homepage",
            sa.String(length=500),
            nullable=True,
            comment="Extension homepage URL",
        ),
        sa.Column(
            "repository",
            sa.String(length=500),
            nullable=True,
            comment="Source code repository URL",
        ),
        sa.Column(
            "license",
            sa.String(length=50),
            nullable=False,
            comment="License identifier",
        ),
        sa.Column(
            "is_built_in",
            sa.Boolean(),
            nullable=False,
            comment="Whether extension is built into the system",
        ),
        sa.Column(
            "is_public",
            sa.Boolean(),
            nullable=False,
            comment="Whether extension can be shared publicly",
        ),
        sa.Column(
            "commands",
            sa.JSON(),
            nullable=False,
            comment="Commands provided by the extension",
        ),
        sa.Column(
            "permissions", sa.JSON(), nullable=False, comment="Required permissions"
        ),
        sa.Column(
            "dependencies", sa.JSON(), nullable=False, comment="Required dependencies"
        ),
        sa.Column(
            "manifest", sa.JSON(), nullable=False, comment="Extension manifest data"
        ),
        sa.Column(
            "code",
            sa.Text(),
            nullable=False,
            comment="Extension JavaScript code (sandboxed)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Extension creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last update timestamp",
        ),
        sa.Column(
            "download_count",
            sa.Integer(),
            nullable=False,
            comment="Number of times downloaded",
        ),
        sa.Column(
            "rating",
            sa.Integer(),
            nullable=False,
            comment="Average user rating (0-500, represents 0.0-5.0 with precision)",
        ),
        sa.Column(
            "security_scan", sa.JSON(), nullable=False, comment="Security scan results"
        ),
        sa.Column(
            "extra_metadata",
            sa.JSON(),
            nullable=False,
            comment="Additional extension metadata",
        ),
        sa.PrimaryKeyConstraint("extension_id"),
    )
    op.create_index("idx_extensions_author", "extensions", ["author"], unique=False)
    op.create_index(
        "idx_extensions_created_at", "extensions", ["created_at"], unique=False
    )
    op.create_index(
        "idx_extensions_name_version", "extensions", ["name", "version"], unique=False
    )
    op.create_index(
        "idx_extensions_public_rating",
        "extensions",
        ["is_public", "rating"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extensions_created_at"), "extensions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_extensions_name"), "extensions", ["name"], unique=True)
    op.create_table(
        "terminal_sessions",
        sa.Column(
            "session_id",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for the session",
        ),
        sa.Column(
            "user_id",
            sa.String(length=36),
            nullable=False,
            comment="Reference to the user who owns the session",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Current session status",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Session creation timestamp",
        ),
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last activity timestamp",
        ),
        sa.Column(
            "terminated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Session termination timestamp",
        ),
        sa.Column(
            "terminal_size",
            sa.JSON(),
            nullable=False,
            comment="Terminal dimensions in columns and rows",
        ),
        sa.Column(
            "working_directory",
            sa.String(length=1024),
            nullable=False,
            comment="Current working directory path",
        ),
        sa.Column(
            "environment_variables",
            sa.JSON(),
            nullable=False,
            comment="Session environment variables",
        ),
        sa.Column(
            "shell_type",
            sa.String(length=50),
            nullable=False,
            comment="Shell type (bash, zsh, fish, etc.)",
        ),
        sa.Column(
            "shell_pid", sa.Integer(), nullable=True, comment="Process ID of the shell"
        ),
        sa.Column(
            "recording_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Whether session recording is active",
        ),
        sa.Column(
            "ai_assistant_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Whether AI assistance is enabled",
        ),
        sa.Column(
            "theme_id",
            sa.String(length=36),
            nullable=True,
            comment="Reference to active theme",
        ),
        sa.Column(
            "extra_metadata",
            sa.JSON(),
            nullable=False,
            comment="Additional session metadata",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_profiles.user_id"]),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        "idx_terminal_sessions_created_at",
        "terminal_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_terminal_sessions_last_active",
        "terminal_sessions",
        ["last_active_at"],
        unique=False,
    )
    op.create_index(
        "idx_terminal_sessions_user_status",
        "terminal_sessions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_terminal_sessions_created_at"),
        "terminal_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_terminal_sessions_last_active_at"),
        "terminal_sessions",
        ["last_active_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_terminal_sessions_status"),
        "terminal_sessions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_terminal_sessions_user_id"),
        "terminal_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "theme_configurations",
        sa.Column(
            "theme_id",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for the theme",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Human-readable theme name",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=False,
            comment="Theme description",
        ),
        sa.Column(
            "version",
            sa.String(length=20),
            nullable=False,
            comment="Theme version (semver format)",
        ),
        sa.Column(
            "author", sa.String(length=100), nullable=False, comment="Theme author name"
        ),
        sa.Column(
            "is_built_in",
            sa.Boolean(),
            nullable=False,
            comment="Whether theme is built into the system",
        ),
        sa.Column(
            "is_public",
            sa.Boolean(),
            nullable=False,
            comment="Whether theme can be shared publicly",
        ),
        sa.Column(
            "colors", sa.JSON(), nullable=False, comment="Color palette configuration"
        ),
        sa.Column("fonts", sa.JSON(), nullable=False, comment="Font configuration"),
        sa.Column(
            "animations", sa.JSON(), nullable=False, comment="Animation settings"
        ),
        sa.Column(
            "cursor", sa.JSON(), nullable=False, comment="Cursor style configuration"
        ),
        sa.Column(
            "background", sa.JSON(), nullable=False, comment="Background configuration"
        ),
        sa.Column(
            "custom_css", sa.Text(), nullable=True, comment="Custom CSS overrides"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Theme creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last update timestamp",
        ),
        sa.Column(
            "download_count",
            sa.Integer(),
            nullable=False,
            comment="Number of times downloaded (public themes)",
        ),
        sa.Column(
            "rating",
            sa.Integer(),
            nullable=False,
            comment="Average user rating (0-500, represents 0.0-5.0 with precision)",
        ),
        sa.Column(
            "extra_metadata",
            sa.JSON(),
            nullable=False,
            comment="Additional theme metadata",
        ),
        sa.PrimaryKeyConstraint("theme_id"),
    )
    op.create_index(
        "idx_theme_configs_created_at",
        "theme_configurations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_theme_configs_name_author",
        "theme_configurations",
        ["name", "author"],
        unique=False,
    )
    op.create_index(
        "idx_theme_configs_public_rating",
        "theme_configurations",
        ["is_public", "rating"],
        unique=False,
    )
    op.create_index(
        op.f("ix_theme_configurations_created_at"),
        "theme_configurations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_theme_configurations_name"),
        "theme_configurations",
        ["name"],
        unique=False,
    )
    op.create_table(
        "user_profiles",
        sa.Column(
            "user_id",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for the user",
        ),
        sa.Column(
            "username", sa.String(length=50), nullable=False, comment="Unique username"
        ),
        sa.Column(
            "email", sa.String(length=255), nullable=False, comment="User email address"
        ),
        sa.Column(
            "display_name",
            sa.String(length=100),
            nullable=False,
            comment="User's display name",
        ),
        sa.Column(
            "avatar_url",
            sa.String(length=500),
            nullable=True,
            comment="User avatar image URL",
        ),
        sa.Column(
            "preferences",
            sa.JSON(),
            nullable=False,
            comment="User preferences and settings",
        ),
        sa.Column(
            "active_theme_id",
            sa.String(length=36),
            nullable=True,
            comment="Currently active theme",
        ),
        sa.Column(
            "default_shell",
            sa.String(length=50),
            nullable=False,
            comment="Default shell preference",
        ),
        sa.Column(
            "keyboard_shortcuts",
            sa.JSON(),
            nullable=False,
            comment="Custom keyboard shortcuts",
        ),
        sa.Column(
            "ai_settings", sa.JSON(), nullable=False, comment="AI assistant preferences"
        ),
        sa.Column(
            "recording_settings",
            sa.JSON(),
            nullable=False,
            comment="Default recording preferences",
        ),
        sa.Column(
            "privacy_settings",
            sa.JSON(),
            nullable=False,
            comment="Privacy and data retention preferences",
        ),
        sa.Column(
            "storage_quota",
            sa.BigInteger(),
            nullable=False,
            comment="Storage quota in bytes",
        ),
        sa.Column(
            "storage_used",
            sa.BigInteger(),
            nullable=False,
            comment="Current storage usage in bytes",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Account creation timestamp",
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last login timestamp",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether account is active",
        ),
        sa.Column(
            "extra_metadata",
            sa.JSON(),
            nullable=False,
            comment="Additional user metadata",
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index("idx_user_profiles_email", "user_profiles", ["email"], unique=False)
    op.create_index(
        "idx_user_profiles_last_login", "user_profiles", ["last_login_at"], unique=False
    )
    op.create_index(
        "idx_user_profiles_storage", "user_profiles", ["storage_used"], unique=False
    )
    op.create_index(
        "idx_user_profiles_username", "user_profiles", ["username"], unique=False
    )
    op.create_index(
        op.f("ix_user_profiles_created_at"),
        "user_profiles",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_profiles_email"), "user_profiles", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_user_profiles_last_login_at"),
        "user_profiles",
        ["last_login_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_profiles_username"), "user_profiles", ["username"], unique=True
    )
    op.create_table(
        "ai_contexts",
        sa.Column(
            "context_id",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for the AI context",
        ),
        sa.Column(
            "session_id",
            sa.String(length=36),
            nullable=False,
            comment="Reference to the terminal session",
        ),
        sa.Column(
            "user_id",
            sa.String(length=36),
            nullable=False,
            comment="Reference to the user",
        ),
        sa.Column(
            "conversation_history",
            sa.JSON(),
            nullable=False,
            comment="Array of AI conversation messages",
        ),
        sa.Column(
            "terminal_context",
            sa.JSON(),
            nullable=False,
            comment="Recent terminal commands and output",
        ),
        sa.Column(
            "user_preferences", sa.JSON(), nullable=False, comment="User AI preferences"
        ),
        sa.Column(
            "model_provider",
            sa.String(length=50),
            nullable=False,
            comment="AI model provider (openai, anthropic, local)",
        ),
        sa.Column(
            "model_name",
            sa.String(length=100),
            nullable=False,
            comment="Specific model name",
        ),
        sa.Column(
            "context_window",
            sa.Integer(),
            nullable=False,
            comment="Maximum context window size",
        ),
        sa.Column(
            "temperature",
            sa.Float(),
            nullable=False,
            comment="AI response randomness (0-1)",
        ),
        sa.Column(
            "max_tokens",
            sa.Integer(),
            nullable=False,
            comment="Maximum response length",
        ),
        sa.Column(
            "system_prompt",
            sa.Text(),
            nullable=False,
            comment="System prompt for AI behavior",
        ),
        sa.Column(
            "last_interaction_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last AI interaction timestamp",
        ),
        sa.Column(
            "token_usage", sa.JSON(), nullable=False, comment="Token usage statistics"
        ),
        sa.Column(
            "settings", sa.JSON(), nullable=False, comment="Additional AI settings"
        ),
        sa.Column(
            "extra_metadata",
            sa.JSON(),
            nullable=False,
            comment="Additional context metadata",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["terminal_sessions.session_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_profiles.user_id"]
        ),
        sa.PrimaryKeyConstraint("context_id"),
    )
    op.create_index(
        "idx_ai_contexts_last_interaction",
        "ai_contexts",
        ["last_interaction_at"],
        unique=False,
    )
    op.create_index(
        "idx_ai_contexts_provider_model",
        "ai_contexts",
        ["model_provider", "model_name"],
        unique=False,
    )
    op.create_index(
        "idx_ai_contexts_user_session",
        "ai_contexts",
        ["user_id", "session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_contexts_last_interaction_at"),
        "ai_contexts",
        ["last_interaction_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_contexts_session_id"), "ai_contexts", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_contexts_user_id"), "ai_contexts", ["user_id"], unique=False
    )
    op.create_table(
        "media_assets",
        sa.Column(
            "asset_id",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for the media asset",
        ),
        sa.Column(
            "session_id",
            sa.String(length=36),
            nullable=False,
            comment="Reference to the terminal session",
        ),
        sa.Column(
            "user_id",
            sa.String(length=36),
            nullable=False,
            comment="Reference to the user who owns the asset",
        ),
        sa.Column(
            "file_name",
            sa.String(length=255),
            nullable=False,
            comment="Original filename",
        ),
        sa.Column(
            "file_path",
            sa.String(length=1024),
            nullable=False,
            comment="Storage path or URL",
        ),
        sa.Column(
            "file_size", sa.BigInteger(), nullable=False, comment="File size in bytes"
        ),
        sa.Column(
            "mime_type", sa.String(length=100), nullable=False, comment="MIME type"
        ),
        sa.Column(
            "media_type",
            sa.String(length=20),
            nullable=False,
            comment="Media type category",
        ),
        sa.Column(
            "dimensions",
            sa.JSON(),
            nullable=True,
            comment="Width and height for images/videos",
        ),
        sa.Column(
            "duration",
            sa.Integer(),
            nullable=True,
            comment="Duration in seconds for videos",
        ),
        sa.Column(
            "thumbnail_path",
            sa.String(length=1024),
            nullable=True,
            comment="Path to generated thumbnail",
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Upload timestamp",
        ),
        sa.Column(
            "last_accessed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last access timestamp",
        ),
        sa.Column(
            "access_count",
            sa.Integer(),
            nullable=False,
            comment="Number of times accessed",
        ),
        sa.Column(
            "is_temporary",
            sa.Boolean(),
            nullable=False,
            comment="Whether asset should be auto-deleted",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Expiration timestamp for temporary assets",
        ),
        sa.Column(
            "security_scan", sa.JSON(), nullable=False, comment="Security scan results"
        ),
        sa.Column(
            "extra_metadata",
            sa.JSON(),
            nullable=False,
            comment="Additional metadata (EXIF, codec info, etc.)",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["terminal_sessions.session_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_profiles.user_id"]
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_index(
        "idx_media_assets_expires_at", "media_assets", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_media_assets_file_size", "media_assets", ["file_size"], unique=False
    )
    op.create_index(
        "idx_media_assets_session_uploaded",
        "media_assets",
        ["session_id", "uploaded_at"],
        unique=False,
    )
    op.create_index(
        "idx_media_assets_user_type",
        "media_assets",
        ["user_id", "media_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_assets_expires_at"), "media_assets", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_last_accessed_at"),
        "media_assets",
        ["last_accessed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_assets_media_type"), "media_assets", ["media_type"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_mime_type"), "media_assets", ["mime_type"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_session_id"), "media_assets", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_uploaded_at"),
        "media_assets",
        ["uploaded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_assets_user_id"), "media_assets", ["user_id"], unique=False
    )
    op.create_table(
        "recordings",
        sa.Column(
            "recording_id",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for the recording",
        ),
        sa.Column(
            "session_id",
            sa.String(length=36),
            nullable=False,
            comment="Reference to the terminal session",
        ),
        sa.Column(
            "user_id",
            sa.String(length=36),
            nullable=False,
            comment="Reference to the user who owns the recording",
        ),
        sa.Column(
            "start_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Recording start timestamp",
        ),
        sa.Column(
            "end_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Recording end timestamp (null if active)",
        ),
        sa.Column(
            "duration",
            sa.Integer(),
            nullable=False,
            comment="Recording duration in milliseconds",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Current recording status",
        ),
        sa.Column(
            "file_size",
            sa.BigInteger(),
            nullable=False,
            comment="Total recording file size in bytes",
        ),
        sa.Column(
            "event_count",
            sa.Integer(),
            nullable=False,
            comment="Total number of recorded events",
        ),
        sa.Column(
            "terminal_size",
            sa.JSON(),
            nullable=False,
            comment="Terminal dimensions during recording",
        ),
        sa.Column(
            "export_formats",
            sa.JSON(),
            nullable=False,
            comment="Available export formats",
        ),
        sa.Column(
            "compression_ratio",
            sa.Integer(),
            nullable=False,
            comment="Compression ratio achieved (percentage)",
        ),
        sa.Column(
            "events", sa.JSON(), nullable=False, comment="Array of recorded events"
        ),
        sa.Column(
            "checkpoints",
            sa.JSON(),
            nullable=False,
            comment="Playback checkpoints for seeking",
        ),
        sa.Column(
            "extra_metadata",
            sa.JSON(),
            nullable=False,
            comment="Additional recording metadata",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["terminal_sessions.session_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_profiles.user_id"]
        ),
        sa.PrimaryKeyConstraint("recording_id"),
    )
    op.create_index(
        "idx_recordings_file_size", "recordings", ["file_size"], unique=False
    )
    op.create_index(
        "idx_recordings_start_time", "recordings", ["start_time"], unique=False
    )
    op.create_index(
        "idx_recordings_user_status", "recordings", ["user_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_recordings_session_id"), "recordings", ["session_id"], unique=True
    )
    op.create_index(
        op.f("ix_recordings_start_time"), "recordings", ["start_time"], unique=False
    )
    op.create_index(
        op.f("ix_recordings_status"), "recordings", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_recordings_user_id"), "recordings", ["user_id"], unique=False
    )
    op.create_table(
        "user_extension_associations",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("extension_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["extension_id"],
            ["extensions.extension_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profiles.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "extension_id"),
    )
    op.create_table(
        "user_theme_associations",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("theme_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["theme_configurations.theme_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profiles.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "theme_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_theme_associations")
    op.drop_table("user_extension_associations")
    op.drop_index(op.f("ix_recordings_user_id"), table_name="recordings")
    op.drop_index(op.f("ix_recordings_status"), table_name="recordings")
    op.drop_index(op.f("ix_recordings_start_time"), table_name="recordings")
    op.drop_index(op.f("ix_recordings_session_id"), table_name="recordings")
    op.drop_index("idx_recordings_user_status", table_name="recordings")
    op.drop_index("idx_recordings_start_time", table_name="recordings")
    op.drop_index("idx_recordings_file_size", table_name="recordings")
    op.drop_table("recordings")
    op.drop_index(op.f("ix_media_assets_user_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_uploaded_at"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_session_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_mime_type"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_media_type"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_last_accessed_at"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_expires_at"), table_name="media_assets")
    op.drop_index("idx_media_assets_user_type", table_name="media_assets")
    op.drop_index("idx_media_assets_session_uploaded", table_name="media_assets")
    op.drop_index("idx_media_assets_file_size", table_name="media_assets")
    op.drop_index("idx_media_assets_expires_at", table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(op.f("ix_ai_contexts_user_id"), table_name="ai_contexts")
    op.drop_index(op.f("ix_ai_contexts_session_id"), table_name="ai_contexts")
    op.drop_index(op.f("ix_ai_contexts_last_interaction_at"), table_name="ai_contexts")
    op.drop_index("idx_ai_contexts_user_session", table_name="ai_contexts")
    op.drop_index("idx_ai_contexts_provider_model", table_name="ai_contexts")
    op.drop_index("idx_ai_contexts_last_interaction", table_name="ai_contexts")
    op.drop_table("ai_contexts")
    op.drop_index(op.f("ix_user_profiles_username"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_last_login_at"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_email"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_created_at"), table_name="user_profiles")
    op.drop_index("idx_user_profiles_username", table_name="user_profiles")
    op.drop_index("idx_user_profiles_storage", table_name="user_profiles")
    op.drop_index("idx_user_profiles_last_login", table_name="user_profiles")
    op.drop_index("idx_user_profiles_email", table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(
        op.f("ix_theme_configurations_name"), table_name="theme_configurations"
    )
    op.drop_index(
        op.f("ix_theme_configurations_created_at"), table_name="theme_configurations"
    )
    op.drop_index("idx_theme_configs_public_rating", table_name="theme_configurations")
    op.drop_index("idx_theme_configs_name_author", table_name="theme_configurations")
    op.drop_index("idx_theme_configs_created_at", table_name="theme_configurations")
    op.drop_table("theme_configurations")
    op.drop_index(op.f("ix_terminal_sessions_user_id"), table_name="terminal_sessions")
    op.drop_index(op.f("ix_terminal_sessions_status"), table_name="terminal_sessions")
    op.drop_index(
        op.f("ix_terminal_sessions_last_active_at"), table_name="terminal_sessions"
    )
    op.drop_index(
        op.f("ix_terminal_sessions_created_at"), table_name="terminal_sessions"
    )
    op.drop_index("idx_terminal_sessions_user_status", table_name="terminal_sessions")
    op.drop_index("idx_terminal_sessions_last_active", table_name="terminal_sessions")
    op.drop_index("idx_terminal_sessions_created_at", table_name="terminal_sessions")
    op.drop_table("terminal_sessions")
    op.drop_index(op.f("ix_extensions_name"), table_name="extensions")
    op.drop_index(op.f("ix_extensions_created_at"), table_name="extensions")
    op.drop_index("idx_extensions_public_rating", table_name="extensions")
    op.drop_index("idx_extensions_name_version", table_name="extensions")
    op.drop_index("idx_extensions_created_at", table_name="extensions")
    op.drop_index("idx_extensions_author", table_name="extensions")
    op.drop_table("extensions")
    # ### end Alembic commands ###
