openapi: 3.0.0
info:
  title: Ebook API
  version: 1.0.0
  description: API for processing and viewing PDF/EPUB files in jterm

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/ebooks/process:
    post:
      summary: Process and validate an ebook file
      description: Validates file, extracts metadata, creates database record, returns ebook ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filePath
              properties:
                filePath:
                  type: string
                  description: Absolute filesystem path to ebook file
                  example: "/home/user/documents/book.pdf"
      responses:
        '200':
          description: Ebook processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EbookMetadata'
        '400':
          description: Invalid file (wrong type, too large, corrupted)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: File not found at specified path
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/ebooks/{ebook_id}/content:
    get:
      summary: Retrieve ebook content
      description: Returns ebook file content for rendering (paginated for large files)
      parameters:
        - name: ebook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
          description: Page number (for PDF pagination)
      responses:
        '200':
          description: Ebook content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Ebook not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/ebooks/{ebook_id}/decrypt:
    post:
      summary: Decrypt password-protected PDF
      description: Attempts to decrypt PDF with provided password
      parameters:
        - name: ebook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  description: PDF password
      responses:
        '200':
          description: Decryption successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  decrypted:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "PDF decrypted successfully"
        '401':
          description: Incorrect password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many password attempts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/ebooks/metadata/{file_hash}:
    get:
      summary: Get ebook metadata by file hash
      description: Retrieve cached metadata using SHA-256 file hash
      parameters:
        - name: file_hash
          in: path
          required: true
          schema:
            type: string
            pattern: '^[a-f0-9]{64}$'
          description: SHA-256 hash of file content
      responses:
        '200':
          description: Metadata found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EbookMetadata'
        '404':
          description: No cached metadata for this hash
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    EbookMetadata:
      type: object
      required:
        - id
        - file_path
        - file_hash
        - file_type
        - file_size
        - is_encrypted
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        file_path:
          type: string
          example: "/home/user/documents/book.pdf"
        file_hash:
          type: string
          example: "a3f5b1c2d4e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2"
        file_type:
          type: string
          enum: [pdf, epub]
        file_size:
          type: integer
          format: int64
          description: File size in bytes
          example: 15728640
        title:
          type: string
          nullable: true
          example: "Python Programming Guide"
        author:
          type: string
          nullable: true
          example: "John Doe"
        total_pages:
          type: integer
          nullable: true
          description: Total pages (PDF only)
          example: 342
        is_encrypted:
          type: boolean
          example: false
        created_at:
          type: string
          format: date-time
          example: "2025-10-09T10:00:00Z"
        last_accessed:
          type: string
          format: date-time
          example: "2025-10-09T10:00:00Z"
        user_id:
          type: string
          format: uuid
          example: "00000000-0000-0000-0000-000000000001"

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "FILE_TOO_LARGE"
        message:
          type: string
          example: "File exceeds 50MB limit"
        details:
          type: object
          additionalProperties: true
